fix: added cypress/.babelrc
Was required since pure cypress run caused:
 `Error: Cannot find module 'next/babel'`

Other attempts to fix https://nextjs.org/docs/messages/failed-loading-swc failed:
 * `swcMinify: false` at `next.config.js`
 * `npm i -D @swc/cli @swc/core`